import random
FLAVORS = ('Almond','Amaretto','Ambrosia','Annisette','Apple','Apple Pie','Bali Hai','Banana','Blackberry','Black Cherry','Blueberry','Blue Hawaii','Blue Orchid','Blue-Raspberry','Bubble Gum','Cantaloupe','Caramel','Cherry','Cherry Kola','Cherry Vanilla','Chocolate','Cinnamon','Coconut','Coffee','Cotton Candy','Cream Soda','Daiquiri','Dill Pickle','Dreamsicle','Fuzzy Navel','Grape','Green Apple','Hawaiian Delight','Hurricane','Ice Cream','Kiwifruit','Lemon','Lemonade','Lemon-Lime','Lemon Meringue','Licorice','Lime','Mai-Tai','Mandarin','Mango','Marachino-Cherry','Margarita','Nectar','Orange','Papaya','Passion Fruit','Pecan','Peach','Peppermint','Pina Colada','Pineapple','Pink Bubblegum','Pink Lemonade','Plum','Praline','Popeye','Raspberry','Root Beer','Rum','Silver Fox','Spearmint','Strawberry','Strawberry-Daiquiri','Strawberry-Shortcake','Sweet Cherry','Tamarind','Tiger\'s Blood','Tropical Punch','Tutti Frutti','Vanilla','Watermelon','Wedding Cake','Wild Blueberry','Wild Cherry','Wild Strawberry')
ANIMALS = ('Aardvark','Albatross','Alligator','Alpaca','Buffalo','Ant','Anteater','Antelope','Ape','Armadillo','Donkey','Baboon','Badger','Barracuda','Bat','Bear','Beaver','Bee','Bison','Boar','Butterfly','Camel','Caribou','Cat','Caterpillar','Cow','Cheetah','Chicken','Chimpanzee','Chinchilla','Clam','Cobra','Cockroach','Cod','Coyote','Crab','Crane','Crocodile','Crow','Deer','Dinosaur','Dog','Dolphin','Dove','Dragonfly','Duck','Eagle','Eel','Elephant','Elk','Emu','Falcon','Ferret','Finch','Fish','Fly','Fox','Frog','Gaur','Gazelle','Gerbil','Panda','Giraffe','Gnat','Gnu','Goat','Goose','Gopher','Gorilla','Grasshopper','Guinea pig','Gull','Hamster','Hare','Hawk','Hedgehog','Heron','Hippopotamus','Hornet','Horse','Hummingbird','Hyena','Iguana','Jackal','Jaguar','Jellyfish','Kangaroo','Koala','Komodo dragon','Lark','Lemur','Leopard','Lion','Llama','Lobster','Locust','Magpie','Mallard','Manatee','Meerkat','Mink','Mole','Monkey','Moose','Mouse','Mosquito','Mule','Narwhal','Newt','Nightingale','Octopus','Opossum','Oryx','Ostrich','Otter','Owl','Ox','Oyster','Panther','Parrot','Pelican','Penguin','Pig','Pigeon','Platypus','Pony','Porcupine','Porpoise','Prairie Dog','Rabbit','Raccoon','Rail','Ram','Rat','Raven','Reindeer','Rhinoceros','Rook','Salamander','Sand Dollar','Sea lion','Sea Urchin','Seahorse','Seal','Shark','Sheep','Shrew','Skunk','Snail','Snake','Spider','Squid','Squirrel','Stinkbug','Swallow','Swan','Tapir','Tarsier','Termite','Tiger','Toad','Trout','Turkey','Turtle','Wallaby','Walrus','Wasp','Weasel','Whale','Wolf','Wombat','Woodpecker','Worm','Wren','Yak','Zebra')
 
def stripclub():
        return('%s %s' % (random.choice(FLAVORS),random.choice(ANIMALS)))
       
if __name__ == '__main__':
		for n in range(25):
			print stripclub()